orgtx2=char(' CUSTOMER COPY','THE RUDY GARDENS','‘99 KENSINGTN  5T','KENSINGTON','WB 55A]','THANK VOU','00:21 ‘00','11 10 14','VISA','oso~v¢..7688', ...
'!@#','SALE EI19 . 15','TRANSACTION CONFIRMED','WITH ','CARDHOLDER SIGNATURE','APPRDVED','iUMuGI‘[ A?lili','N','Am! tiiu; I1 mm!','PLEASE ',' AIN RECEIPT');
orgtx1='MIDDLEBOROUGH';
orgtx3=char(' .',',. HYUNDAI','-1»; I10 IS THE ‘','   w',' ;:?',' MOST AWARDED,  w','=CAR OF THE ‘', ...
'.YEAR 2008 *"?-.~','‘     I 10_ !,__........_g','jn3—‘1, .')

orgtx4=char('We re‘ ,\ \NOT JUST ~ ~ROLL NUMBER :. r-',':,.BUT UNIQUE INDIVIDUAL^%$','MOUNT  LITERA','…*MOUNTLITERA..','ZEE SCHooL','-»x~;', ...
'n.,n\G reat SCHOOL ,..GREAT FUTURE..mm,','‘ ,  co _:','? _ In’ Registration Open','  .for 2015-16.','m,w_Wm_/M W ‘  _ =..=..,,....m....m..s..,,',...
': 1 ‘ \MOUNT LTERA ZEE SCHooL.. DEHRADUN','-»x~;,n.,n\ M W ‘  _ =.‘.=..‘,,....');

orgtx5=char('INCOME TAX DEPARTMENT  GOVT. OF INDIA','Permanent Account Number Card j.|_-_f','W ABCDE1234F E-.rE.IE',', .','7:}/"APPLICANT NAME', ... 
'‘Rm mm /Fathers Name','AP.‘PLICANT’S FATHER NAME','3;: jgl?léf?al o ','01/06/1995  I Signature');

orgtx6=char('g T0--—~',' _  =IT‘f/ Name:','‘a_ ‘ Surprit Kaur','‘ 3‘ ‘ a=.=rar?2§./ DOB: 091 21 989', ... 
'$ - / Male ‘7 “‘F~"“" 1“','18oo.12oo.13o1 .,. mags-','— _m 31:11??-','ADHAR CARD MAKER PRANK')

orgtx7=char('-3G1:','COFFEE I','I','1 m SKIM LATT E 3.5o','1 RASBERRY SCONE 4.oo', ...
'TAX .5o','TOTAL 8.oo','m /,.,,','^&*8  …f');
