tx2=char(' CUSTOMER COPY','THE RUDY GARDENS','‘99 KENSINGTN  5T','KENSINGTON','WB 55A]','THANK VOU','00:21 ‘00','11 10 14','VISA','oso~v¢..7688', ...
'!@#','SALE EI19 . 15','TRANSACTIDN CONFIRMED','WITH ','CARDHOLDER SIGNATURE','APPRDVED','iUMuGI‘[ A?lili','N','Am! tiiu; I1 mm!','PLEASE ',' AIN RECEIPT');
tx1='MIDDLEBOROUGH';
tx3=char(' .',',. HYUNDAI','-1»; I10 IS THE ‘','   w',' ;:?',' MOST AWARDED,  w','=CAR OF TH3 ‘', ...
'.YEAR 2008 *"?-.~','‘     I 10_ !,__........_g','jn3—‘1, .')

tx4=char('We rv‘ ,\ \NOT JUST ~ ~ROLL NUMBER :. r-',':,.BUT UNIQUE INDIVIDUAL^%$','MOUNT  LITERA','…*MOUNT ITERA..','ZEE 5CHooL','-»x~;', ...
'n.,n\Gmreat 5CHOOL ,..G5EAT FUIUFE..mm,','‘ ,  co _:','? _ In’ Registration Open','  .for 2015-16.','m,w_Wm_/M W ‘  _ =..=..,,....m....m..s..,,',...
': 1 ‘ \MOINT LTERA Z33 5CHooL.. DOHRQDUN','-»x~;,n.,n\ M W ‘  _ =.‘.=..‘,,....');

tx5=char('INCOME TAX DEPARTMENT  GOVT. OF INDIA','Permanent Account Number Card j.|_-_f','W ABCDE1234F E-.rE.IE',', .','7:}/"APPLICANT NAME', ... 
'‘Rm mm /Fathers Name','AF.‘PL|CANT’S FAlHER NAME','3;: jgl?léf?al o ','01/06/1995  I Signature');

tx6=char('g T0--—~',' _  =IT‘f/ Name:','‘a_ ‘ Surprit Kaur','‘ 3‘ ‘ a=.=rar?2§./ DOB: 094 24 989', ... 
'$ - / Male ‘7 “‘F~"“" 1“','1soo.12oo.13o1 .,. mags-','— _m 31:11??-','ADHAR CARD MAKER FRANK')

tx7=char('-3G1:','COFFEE I','I','1 m SKIM LATTIE 3.So','1 RASBERRY SEONE 4.oo', ...
'TAX .So','TOIAL 8.oo','m /,.,,','^&*8  …f');
